### ISSUE TITLE
OSErrors during tile loads

### ISSUE THREAD

**Issue by jmillxyz** [shongololo/aiovectortiler#10]
While loading tiles, received OSError [Errno41] and OSError [Errno 42], see below. Not sure what causes it, but it looks like the tile in question (12/927/1697.pbf) is never actually returned.

```
...
INFO:aiohttp.access:127.0.0.1 - - [19/Aug/2016:14:29:21 +0000] "GET /all/14/3709/6791.pbf HTTP/1.1" 200 27089 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
INFO:aiohttp.access:127.0.0.1 - - [19/Aug/2016:14:29:25 +0000] "GET /all/12/926/1698.pbf HTTP/1.1" 200 205117 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
INFO:aiohttp.access:127.0.0.1 - - [19/Aug/2016:14:29:27 +0000] "GET /all/12/927/1698.pbf HTTP/1.1" 200 283729 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
ERROR:asyncio:Fatal write error on socket transport
protocol: <RequestHandler GET:/all/12/926/1697.pbf connected>
transport: <_SelectorSocketTransport fd=18 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 707, in write
    n = self._sock.send(data)
OSError: [Errno 41] Protocol wrong type for socket
ERROR:aiohttp.web:Error handling request
Traceback (most recent call last):
  File "/Users/jonmiller/.virtualenvs/aiovectortiler/lib/python3.5/site-packages/aiohttp/server.py", line 285, in start
    yield from self.handle_request(message, payload)
  File "/Users/jonmiller/.virtualenvs/aiovectortiler/lib/python3.5/site-packages/aiohttp/web.py", line 100, in handle_request
    yield from resp.write_eof()
  File "/Users/jonmiller/.virtualenvs/aiovectortiler/lib/python3.5/site-packages/aiohttp/web_reqrep.py", line 862, in write_eof
    self.set_tcp_nodelay(True)
  File "/Users/jonmiller/.virtualenvs/aiovectortiler/lib/python3.5/site-packages/aiohttp/web_reqrep.py", line 625, in set_tcp_nodelay
    self._resp_impl.transport.set_tcp_nodelay(value)
  File "/Users/jonmiller/.virtualenvs/aiovectortiler/lib/python3.5/site-packages/aiohttp/parsers.py", line 256, in set_tcp_nodelay
    self._socket.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, value)
OSError: [Errno 22] Invalid argument
INFO:aiohttp.access:127.0.0.1 - - [19/Aug/2016:14:29:32 +0000] "GET /all/12/926/1697.pbf HTTP/1.1" 500 170 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
ERROR:asyncio:Fatal write error on socket transport
protocol: <RequestHandler GET:/all/12/927/1697.pbf connected>
transport: <_SelectorSocketTransport fd=19 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 707, in write
    n = self._sock.send(data)
OSError: [Errno 41] Protocol wrong type for socket
ERROR:aiohttp.web:Error handling request
Traceback (most recent call last):
  File "/Users/jonmiller/.virtualenvs/aiovectortiler/lib/python3.5/site-packages/aiohttp/server.py", line 285, in start
    yield from self.handle_request(message, payload)
  File "/Users/jonmiller/.virtualenvs/aiovectortiler/lib/python3.5/site-packages/aiohttp/web.py", line 100, in handle_request
    yield from resp.write_eof()
  File "/Users/jonmiller/.virtualenvs/aiovectortiler/lib/python3.5/site-packages/aiohttp/web_reqrep.py", line 862, in write_eof
    self.set_tcp_nodelay(True)
  File "/Users/jonmiller/.virtualenvs/aiovectortiler/lib/python3.5/site-packages/aiohttp/web_reqrep.py", line 625, in set_tcp_nodelay
    self._resp_impl.transport.set_tcp_nodelay(value)
  File "/Users/jonmiller/.virtualenvs/aiovectortiler/lib/python3.5/site-packages/aiohttp/parsers.py", line 256, in set_tcp_nodelay
    self._socket.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, value)
OSError: [Errno 22] Invalid argument
INFO:aiohttp.access:127.0.0.1 - - [19/Aug/2016:14:29:41 +0000] "GET /all/12/927/1697.pbf HTTP/1.1" 500 170 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
```

**Comment by jmillxyz** [comment]
Subsequent loads seem to work fine... Not sure!

**Comment by songololo** [comment]
I haven't seen this behaviour before but please let me know if it reoccurs.
