### ISSUE TITLE
KeyError: bbox when using `clip: true` in recipe

### ISSUE THREAD

**Issue by jmillxyz** [shongololo/aiovectortiler#8]
Looks like you've already marked some of the related lines with `#noqa` so I assume that means they're not tested to the same levels as other code, but I'm getting the following error when attempting to use `clip: true` in my recipe.

Here's the error:

```
ERROR:aiohttp.web:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 285, in start
    yield from self.handle_request(message, payload)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web.py", line 90, in handle_request
    resp = yield from handler(request)
  File "/aiovectortiler/aiovectortiler/serve.py", line 85, in request_pbf
    return await ServePBF.serve(request)
  File "/aiovectortiler/aiovectortiler/tile_handler.py", line 75, in serve
    layer_data.append(await cls.query_layer(layer, zoom, west, south, east, north))
  File "/aiovectortiler/aiovectortiler/tile_handler.py", line 96, in query_layer
    sql = cls.sql(query, zoom, west, south, east, north)
  File "/aiovectortiler/aiovectortiler/tile_handler.py", line 119, in sql
    geometry = geometry.format(way='way')
KeyError: 'bbox'
```

As best I can tell, the north, south, east, west parameters are never created.

As a workaround, I believe doing `WHERE geom && !bbox!` in the SQL query would achieve the same effect. Can you confirm?

**Comment by songololo** [comment]
The string formatting parameters were missing so I've added them. Not yet tested.

**Comment by songololo** [comment]
I'll need to investigate the intent of the clipping behaviour in utilery as I'm not sure that the addition of ST_Intersection is doing much. Perhaps a ST_Split action is required.
